steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -f, scicode/verified.Dockerfile, -t, '${_SANDBOX_IMAGE}', .]
images: ['${_SANDBOX_IMAGE}']
substitutions:
  _SANDBOX_IMAGE: us-central1-docker.pkg.dev/openevalz-sbx-84737/openevalz/eval-scicode-verified-sandbox:1.0.0
timeout: 3600s
